### ISSUE TITLE
Value Error: Axes don't match array!

### ISSUE THREAD

**Issue by nicolaferrari96** [nshaud/DeepNetsForEO#33]
Hello, I execute without problems convert_gt.py, extract_images.py.
When I execute create_lmdb.py irrg_train_lmdb work correctly, but the labels_train_lmdb give me that error: 

> `=== Creating LMDB for path/to/labels_train/ ===
>   0%|                                                                                                                | 0/57549 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "create_lmdb.py", line 121, in <module>
>     create_label_lmdb(target_folder, samples)
>   File "create_lmdb.py", line 94, in create_label_lmdb
>     label = label.transpose((2,0,1))
> ValueError: axes don't match array

**Comment by nicolaferrari96** [comment]
Problem solved.
during the execution of convert_gt I made a mistake with the path.
The correct Path is ISPRS_semantic_labeling_Vaihingen/gts_for_participants for Vaihingen data set.
